### ISSUE TITLE
Templetize zlib.output_compression

### ISSUE THREAD

**Issue by jimmykarily** [paketo-buildpacks/php-web#124]
## What happened?

This buildpack includes a php.ini file that has zlib.output_compression set to "Off" with no way to enable it: https://github.com/paketo-buildpacks/php-web/blob/main/config/php-ini.go#L288

Since the php.ini file is already a template, is it easy to accept an option in buildpack.yml to enable zlib compression.

* What were you attempting to do?

Create an image for Wordpress 5.6.1:

```
pack build wordpress  --builder paketobuildpacks/builder:full
```

with a directory structure like (htdocs is the extracted wordpress code):

```
$ ls .
buildpack.yml htdocs
```
and buildpack.yml:

```
---
php:
  script: index.php
  webserver: nginx
  webdirectory: htdocs
```

* What did you expect to happen?

The built image should run fine.

* What was the actual behavior? Please provide log output, if possible.

The image builds fine but when trying to run it I get the error:

```
2021/02/15 14:04:36 [error] 24#0: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function gzinflate() in /workspace/source/app/htdocs/wp-includes/class-requests.php:949
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

pack version: `0.17.0+git-d9cb4e7.build-2045`

* What buildpacks are you using? Please include versions

PHP 0.1.1

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
upstream builder image: `paketobuildpacks/builder@sha256:6ecfb5504194ca78d72ab760baa3e7547abb89febc731865c629e469bc6371f6`

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

see above

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by jimmykarily** [comment]
I manually edited the php.ini file and the error still occurs (edited the file, committed the image and run the updated image). There must be something more missing.

**Comment by jimmykarily** [comment]
For reference, here is what phpinfo() returns:
![image](https://user-images.githubusercontent.com/2794419/108053607-4dd16900-7056-11eb-825f-67171d1fbcc5.png)

It seems that PHP_EXTENSION_DIR  is pointing to a directory where I can indeed find a zlib.so file (`/layers/paketo-buildpacks_php-dist/php/lib/php/extensions/no-debug-non-zts-20190902 `). I'd don't know what else could be wrong. Maybe some mixin is missing here: https://github.com/paketo-buildpacks/php-dist/blob/main/buildpack.toml#L96 ? 

of maybe php shouldn't be configured with `'--with-zlib=shared'` (which is reported in the third row of phpinfo()) ? Any help is welcome.

**Comment by jimmykarily** [comment]
ok simply putting this in the `php.ini` makes it work (did it manually and commited the container as a new docker image):

```
extension=zlib.so
```

no other change needed to the image produced by the buildpack. The question is how can I change the php.ini file from buildpack.yml (or other method).

**Comment by jimmykarily** [comment]
Shouldn't it be possible to set 'Extensions'  here as ? https://github.com/paketo-buildpacks/php-web/blob/236f02a18bd70dca08e547f906e1cb3f40120e0a/features/php.go#L48

Possible as `p.bpYAML.Config.Extensions` or something like that?

ref: https://github.com/paketo-buildpacks/php-web/blob/236f02a18bd70dca08e547f906e1cb3f40120e0a/config/config.go#L86

**Comment by arjun024** [comment]
@jimmykarily See [Paketo docs about PHP_INI_SCAN_DIR ](https://paketo.io/docs/buildpacks/language-family-buildpacks/php/#php_ini_scan_dir) - it sets the scan directory to `<APP-ROOT>/.php.ini.d`. You should be able to leverage this by creating a directory named `.php.ini.d` and adding `.ini` files there. See [an example](https://github.com/paketo-buildpacks/php-web/tree/v0.0.138/integration/testdata/php_modules). Does that solve your issue?

**Comment by jimmykarily** [comment]
@arjun024  yes it does! I didn't realize the importance of that section in docs. Maybe a text about "enabling PHP extensions" would help there, since that's what one would search for and there are no terms leading Search engines to that section in docs.

Thanks for the spot on solution. I will close this issue and the linked PR. The PR still adds the functionality to enable through the buildpack.yml so let me know if you prefer me to fix it (fails integration tests currently) and re-open it.

**Comment by arjun024** [comment]
@jimmykarily Thanks for bringing this to attention. I'll make it a point to explicitly state it in the README.
Regarding buildpack.yml - The Paketo community consensus is to move away from buildpack.yml to build-time environment variables as a means for user configuration.<sup>[[1]](https://github.com/paketo-buildpacks/go-build/blob/main/rfcs/0003-buildpack-yml-to-env-var.md)[[2]](https://github.com/paketo-buildpacks/dotnet-core/blob/main/rfcs/0000-buildpack-yml-to-env-var.md)[[3]](https://github.com/paketo-buildpacks/nodejs/blob/main/rfcs/0003-buildpack-yml-to-env-var.md)</sup> So adding more config options there wouldn't be ideal.
