### ISSUE TITLE
Support "listen ssl" directive in generated nginx.conf

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/php-web#139]
### What happened?

I'm trying to create a php app that uses nginx for SSL enabled http server. Right now I am able to do this by creating 
a `<app>/.nginx.conf.d/custom-server.conf` with the following content:
```
ssl on;

ssl_certificate path/to/cert.pem;
ssl_certificate_key path/to//key.pem;
```
just like [this](https://github.com/paketo-buildpacks/php-web/blob/v0.0.138/integration/testdata/simple_app_nginx_custom_cfg/.nginx.conf.d/custom-server.conf).

**But**, the `ssl` directive is deprecated since 1.15.0. See http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl
The alternative is to have the listen directive include the ssl param like the following example:
```
listen 443 ssl;
```

However, this is not supported by this buildpack. See https://github.com/paketo-buildpacks/php-web/blob/v0.0.138/config/nginx.go#L154 - it does not allow the user to provide a configuration to add the "ssl" directive.

### What do I expect?

I expect that the new way of turning os ssl is supported as a configuration option, and I don't see the following in the logs:
```
 [warn] 29#0: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /workspace/.nginx.conf.d/custom-server.conf:1
```

**Comment by arjun024** [comment]
Not high priority as there's way around this

**Comment by TisVictress** [comment]
@arjun024 Is there an update on the priority of this issue? After checking the [changelog](https://nginx.org/en/CHANGES#:~:text=Change%3A%20the%20%22ssl%22-,directive,-is%20deprecated%3B%20the), it doesn't look like the ssl directive is unsupported yet so the workaround above will still work.

**Comment by arjun024** [comment]
I'd say still the same priority
