### ISSUE TITLE
Update README.md to reflect valid PHP versions

### ISSUE THREAD

**Issue by oscarnevarezleal** [paketo-buildpacks/php-web#145]
## What happened?

README.md has the wrong PHP version on the example shown ( 10.x )

* What were you attempting to do?
I was about to send a PR but I wanted to create the issue first.

* What did you expect to happen?
Update the file

* What was the actual behavior? Please provide log output, if possible.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by arjun024** [comment]
It's simply demonstrating an example of semver version syntax

**Comment by arjun024** [comment]
Happy to accept a better example in the Readme!

**Comment by oscarnevarezleal** [comment]
There it goes.
