### ISSUE TITLE
Provide a FORCE_HTTPS option

### ISSUE THREAD

**Issue by CAFxX** [paketo-buildpacks/php-web#3]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
capi 2.95.0

What version of the buildpack you are using?
master

If you were attempting to accomplish a task, what was it you were attempting to do?
Force redirect HTTP to HTTPS

What did you expect to happen?
Ideally, a mechanism similar to the one provided by the staticfile buildpack ([FORCE_HTTPS](https://docs.cloudfoundry.org/buildpacks/staticfile/index.html#config-options)). As an example, a FORCE_HTTPS option in `options.json` that automatically sets the relevant configuration in either apache or nginx would be the ideal outcome.

What was the actual behavior?
As a user, I have to know specifics about SSL termination done by my platform operator and I have to write custom httpd/nginx configuration

**Comment by tillyt** [comment]
Closing this issue as it's been transferred to other repo

**Comment by dmikusa-pivotal** [comment]
@tillyt - where did this get moved? Do you have a link for reference? Thanks

**Comment by tillyt** [comment]
@dmikusa-pivotal that was a mistake, thanks!

**Comment by dmikusa-pivotal** [comment]
This has been fixed in the PHP Web CNB: https://github.com/paketo-buildpacks/php-web/pull/10

I think we can close this issue now.
